version: '3.6'
services: 
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: goGin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes: 
      - /d/docker-mount/docker-compose:/var/lib/postgresql
    ports:
      - 9999:5432
  api:
    image: gogin-web:v.1.0.1
    ports:
      - 8888:80
    environment: 
      - test=docker
      - NODE_ENV=docker
      - PORT=80
      ## DB config
      - pgHost=postgres
      - pgPost=5432
      - pgDBName=goGin
      - pgUsername=postgres
      - pgPassword=admin
    depends_on:
      - postgres
    links:
      - postgres