app:
    env:  "development"
    NODE_ENV:  "development"
    port: 8081
    debug: true
database:
    mysql:
        ip: "127.0.0.1"
        port: "32769"
        dbname: "ginmysql"
        username: "root"
        password: ""
    psql:
        ip: "127.0.0.1"
        port: "9999"
        dbname: "goGin"
        username: "postgres"
        password: "admin"