app:
    env:  "development"
    port: 8081
    debug: true
database:
    mysql:
        ip: "127.0.0.1"
        port: "32769"
        dbname: "ginmysql"
        username: "root"
        password: ""
    psql:
        # HOST PORT LOCAL
        ip: "127.0.0.1"
        port: "9999"
        # HOST PORT DOCKER_COMPOSE
        # ip: "postgres"
        # port: "5432"
        dbname: "goGin"
        username: "postgres"
        password: "admin"